// 役割: EF Coreが現在のモデル構成を記録するスナップショットです。
// マイグレーション生成時に参照されるため、通常は手編集せずモデル変更から再生成します。
// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using 中央競馬.共通.Data;

#nullable disable

namespace 共通.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("中央競馬.共通.Models.リアルタイムオッズモデル", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("レース番号")
                        .HasColumnType("int");

                    b.Property<int>("人気")
                        .HasColumnType("int");

                    b.Property<double>("単勝オッズ")
                        .HasColumnType("float");

                    b.Property<DateTime>("日時")
                        .HasColumnType("datetime2");

                    b.Property<string>("複勝オッズ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("複勝オッズ_MAX")
                        .HasColumnType("float");

                    b.Property<double>("複勝オッズ_MIN")
                        .HasColumnType("float");

                    b.Property<string>("開催場所")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateOnly>("開催日")
                        .HasColumnType("date");

                    b.Property<string>("馬名")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("馬番")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("開催日", "開催場所", "レース番号", "馬名", "馬番")
                        .HasDatabaseName("IX_開催日_開催場所_レース番号_馬名_馬番");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("開催日", "開催場所", "レース番号", "馬名", "馬番"), new[] { "日時", "単勝オッズ", "複勝オッズ", "複勝オッズ_MIN", "複勝オッズ_MAX" });

                    b.ToTable("リアルタイムオッズ");
                });

            modelBuilder.Entity("中央競馬.共通.Models.レース情報モデル", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("コース種別")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("レース番号")
                        .HasColumnType("int");

                    b.Property<decimal>("一着賞金")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<decimal>("三着賞金")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<decimal>("二着賞金")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<decimal>("五着賞金")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<string>("周回方向")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("四着賞金")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<string>("変更情報")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("天候")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("性別")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<float>("斤量")
                        .HasColumnType("real");

                    b.Property<float>("斤量増減")
                        .HasColumnType("real");

                    b.Property<string>("条件")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("枠番")
                        .HasColumnType("int");

                    b.Property<string>("毛色")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("減量記号")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("発走時刻")
                        .HasColumnType("datetime2");

                    b.Property<int>("着順")
                        .HasColumnType("int");

                    b.Property<string>("競走名")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("調教師")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("調教師情報URL")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("調教師所属")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("距離")
                        .HasColumnType("int");

                    b.Property<string>("開催場所")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateOnly>("開催日")
                        .HasColumnType("date");

                    b.Property<string>("馬主")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("馬体重")
                        .HasColumnType("int");

                    b.Property<int>("馬体重増減")
                        .HasColumnType("int");

                    b.Property<string>("馬名")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("馬場")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("馬情報URL")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("馬番")
                        .HasColumnType("int");

                    b.Property<int>("馬齢")
                        .HasColumnType("int");

                    b.Property<string>("騎手")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("騎手情報URL")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("騎手所属")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("開催日", "開催場所", "レース番号", "馬名")
                        .HasDatabaseName("IX_開催日_開催場所_レース番号_馬名");

                    b.ToTable("レース情報");
                });

            modelBuilder.Entity("中央競馬.共通.Models.出馬表モデル", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("コース種別")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("レース番号")
                        .HasColumnType("int");

                    b.Property<int>("一コーナー")
                        .HasColumnType("int");

                    b.Property<decimal>("一着賞金")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("一着馬着差タイム")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("三コーナー")
                        .HasColumnType("int");

                    b.Property<decimal>("三着賞金")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("上り3F")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("二コーナー")
                        .HasColumnType("int");

                    b.Property<decimal>("二着賞金")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("五着賞金")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("休み明け判定")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal>("先着馬着差タイム")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("前走Id")
                        .HasColumnType("int");

                    b.Property<decimal>("前走上り3F")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("前走場所")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateOnly>("前走日")
                        .HasColumnType("date");

                    b.Property<string>("前走間隔")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("周回方向")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("周回方向変化")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("四コーナー")
                        .HasColumnType("int");

                    b.Property<decimal>("四着賞金")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("変更情報")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("天候")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("平均間隔")
                        .HasColumnType("int");

                    b.Property<decimal>("後着馬着差タイム")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("性別")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<float>("斤量")
                        .HasColumnType("real");

                    b.Property<float>("斤量増減")
                        .HasColumnType("real");

                    b.Property<float>("斤量差")
                        .HasColumnType("real");

                    b.Property<string>("条件")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("枠番")
                        .HasColumnType("int");

                    b.Property<int?>("標準偏差")
                        .HasColumnType("int");

                    b.Property<string>("毛色")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("減量記号")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("発走時刻")
                        .HasColumnType("datetime2");

                    b.Property<string>("着差")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("着順")
                        .HasColumnType("int");

                    b.Property<string>("競走名")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("調教師")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("調教師情報URL")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("調教師所属")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<decimal>("走破時計")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("距離")
                        .HasColumnType("int");

                    b.Property<string>("距離差")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("距離延短")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("開催場所")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateOnly>("開催日")
                        .HasColumnType("date");

                    b.Property<string>("馬主")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("馬体重")
                        .HasColumnType("int");

                    b.Property<int>("馬体重増減")
                        .HasColumnType("int");

                    b.Property<string>("馬名")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("馬場")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("馬情報URL")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("馬番")
                        .HasColumnType("int");

                    b.Property<int>("馬齢")
                        .HasColumnType("int");

                    b.Property<string>("騎手")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("騎手情報URL")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("騎手所属")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("一着賞金")
                        .HasDatabaseName("IX_Id_一着賞金");

                    b.ToTable("出馬表");
                });

            modelBuilder.Entity("中央競馬.共通.Models.変更情報モデル", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("レース番号")
                        .HasColumnType("int");

                    b.Property<string>("変更内容")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("変更区分")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("変更理由")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("開催場所")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateOnly>("開催日")
                        .HasColumnType("date");

                    b.Property<string>("馬名")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("馬番")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("開催日", "開催場所", "レース番号")
                        .HasDatabaseName("IX_開催日_開催場所_レース番号");

                    b.HasIndex("開催日", "開催場所", "レース番号", "馬名")
                        .HasDatabaseName("IX_開催日_開催場所_レース番号_馬名");

                    b.ToTable("変更情報");
                });

            modelBuilder.Entity("中央競馬.共通.Models.当日メニューモデル", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("レース番号")
                        .HasColumnType("int");

                    b.Property<string>("出馬表URL")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("周回方向")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("変更")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("天候")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("成績URL")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("発走時刻")
                        .HasColumnType("datetime2");

                    b.Property<string>("競走名")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("競走種類")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("距離")
                        .HasColumnType("int");

                    b.Property<string>("開催場所")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateOnly>("開催日")
                        .HasColumnType("date");

                    b.Property<int>("頭数")
                        .HasColumnType("int");

                    b.Property<string>("馬場")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("開催日", "開催場所", "レース番号")
                        .HasDatabaseName("IX_開催日_開催場所_レース番号");

                    b.ToTable("当日メニュー");
                });

            modelBuilder.Entity("中央競馬.共通.Models.払戻金モデル", b =>
                {
                    b.Property<DateOnly>("開催日")
                        .HasColumnType("date");

                    b.Property<string>("開催場所")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("レース番号")
                        .HasColumnType("int");

                    b.Property<string>("馬券")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("組番")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("金額")
                        .HasColumnType("decimal(10, 0)");

                    b.HasKey("Id");

                    b.HasIndex("開催日", "開催場所", "レース番号", "馬券", "組番")
                        .IsUnique()
                        .HasDatabaseName("IX_払戻金_開催日_開催場所_レース番号_馬券_組番");

                    b.ToTable("払戻金");
                });

            modelBuilder.Entity("中央競馬.共通.Models.競走結果モデル", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("レース番号")
                        .HasColumnType("int");

                    b.Property<int>("一コーナー")
                        .HasColumnType("int");

                    b.Property<decimal>("一着馬着差タイム")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("三コーナー")
                        .HasColumnType("int");

                    b.Property<decimal>("上り3F")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("二コーナー")
                        .HasColumnType("int");

                    b.Property<decimal>("先着馬着差タイム")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("四コーナー")
                        .HasColumnType("int");

                    b.Property<decimal>("後着馬着差タイム")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("枠番")
                        .HasColumnType("int");

                    b.Property<string>("着差")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("着順")
                        .HasColumnType("int");

                    b.Property<decimal>("走破時計")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("開催場所")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateOnly>("開催日")
                        .HasColumnType("date");

                    b.Property<string>("馬名")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("馬番")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("競走結果");
                });

            modelBuilder.Entity("中央競馬.共通.Models.開催情報モデル", b =>
                {
                    b.Property<DateOnly>("開催日")
                        .HasColumnType("date");

                    b.Property<string>("開催場所")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("当日メニューURL")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("開催日", "開催場所");

                    b.ToTable("開催情報");
                });

            modelBuilder.Entity("中央競馬.共通.Models.馬情報モデル", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("中央付加賞金")
                        .HasColumnType("int");

                    b.Property<int>("中央収得賞金")
                        .HasColumnType("int");

                    b.Property<int>("地方収得賞金")
                        .HasColumnType("int");

                    b.Property<string>("性別")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("所属")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateOnly>("更新日")
                        .HasColumnType("date");

                    b.Property<string>("母")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("母母")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("母父")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("毛色")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("父")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("父母")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("父父")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<DateOnly>("生年月日")
                        .HasColumnType("date");

                    b.Property<string>("生産牧場")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("産地")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("調教師")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("馬主")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("馬名")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("Id");

                    b.HasIndex("調教師")
                        .HasDatabaseName("IX_調教師");

                    b.HasIndex("馬主")
                        .HasDatabaseName("IX_馬主");

                    b.HasIndex("馬名", "調教師")
                        .HasDatabaseName("IX_馬名_調教師");

                    b.HasIndex("馬名", "更新日")
                        .HasDatabaseName("IX_馬名_更新日");

                    b.HasIndex("馬名", "生年月日", "父")
                        .IsUnique()
                        .HasDatabaseName("IX_馬名_生年月日_父");

                    b.ToTable("馬情報");
                });
#pragma warning restore 612, 618
        }
    }
}
