SET NOCOUNT ON;
PRINT '=== 厩舎の話 列 ===';
SELECT STRING_AGG(COLUMN_NAME,', ') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='厩舎の話';
PRINT '=== 調教 列 ===';
SELECT STRING_AGG(COLUMN_NAME,', ') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='調教';
