SELECT STRING_AGG(COLUMN_NAME, N', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=N'レース情報';
SELECT TOP 5 条件, 競走名, 一着賞金, 馬齢, 斤量, 馬体重, 騎手, 調教師 FROM レース情報 WHERE 開催場所=N'東京' AND 着順>0 ORDER BY 開催日 DESC;
