SELECT STRING_AGG(COLUMN_NAME, N', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=N'払戻金';
SELECT TOP 12 * FROM 払戻金 WHERE 開催場所=N'東京' ORDER BY 開催日 DESC, レース番号;
SELECT YEAR(開催日) yy, COUNT(1) n, COUNT(DISTINCT CONCAT(開催日,'-',レース番号)) R FROM 払戻金 WHERE 開催場所=N'東京' GROUP BY YEAR(開催日) ORDER BY yy;
