-- 払戻系テーブルの在庫確認
SELECT t.TABLE_NAME, (SELECT COUNT(1) FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME=t.TABLE_NAME) 列数
FROM INFORMATION_SCHEMA.TABLES t
WHERE t.TABLE_TYPE='BASE TABLE' AND (t.TABLE_NAME LIKE N'%払戻%' OR t.TABLE_NAME LIKE N'%配当%' OR t.TABLE_NAME LIKE N'%payout%' OR t.TABLE_NAME LIKE N'%オッズ%' OR t.TABLE_NAME LIKE N'%馬連%' OR t.TABLE_NAME LIKE N'%ワイド%' OR t.TABLE_NAME LIKE N'%三連%' OR t.TABLE_NAME LIKE N'%3連%')
ORDER BY t.TABLE_NAME;
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' ORDER BY TABLE_NAME;
