SELECT N'レース情報_列' k, STRING_AGG(COLUMN_NAME, N', ') v FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=N'レース情報'
UNION ALL
SELECT N'リアルタイムオッズ_列', STRING_AGG(COLUMN_NAME, N', ') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=N'リアルタイムオッズ'
UNION ALL
SELECT N'コンピ指数_列', STRING_AGG(COLUMN_NAME, N', ') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=N'コンピ指数';
